# Generated by Django 3.1.2 on 2020-11-01 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_manager', '0002_remove_file_file_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='aws_size',
            field=models.BigIntegerField(),
        ),
    ]
