# Generated by Django 3.1.2 on 2020-11-03 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file_manager', '0005_auto_20201103_1334'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='directory',
            options={'verbose_name_plural': 'Directories'},
        ),
        migrations.AlterUniqueTogether(
            name='file',
            unique_together={('directory', 'aws_key')},
        ),
    ]
