# Generated by Django 3.1.2 on 2020-11-05 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('file_manager', '0007_auto_20201104_0755'),
    ]

    operations = [
        migrations.AddField(
            model_name='directory',
            name='parent_directory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nested_directories', to='file_manager.directory'),
        ),
    ]
