# Generated by Django 3.1.2 on 2020-11-05 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_manager', '0008_directory_parent_directory'),
    ]

    operations = [
        migrations.AddField(
            model_name='directory',
            name='nested',
            field=models.BooleanField(default=False),
        ),
    ]
